### ISSUE TITLE
Incorrect data getting converted for int/long data type

### ISSUE THREAD

**Issue by ss23697** [AbsaOSS/cobrix#216] opened 2019-11-19 07:13 UTC
Hi team,

We are seeing incorrect data like ‘ABCDE’ for column having copybook data type as PIC 9(08) getting converted to ‘12345’ in spark dataframe.

Could you please help in resolving this issue?

Thanks
Subahnkar Sen

**Comment by yruslan** [comment] 2019-11-19 08:34
Hi, thanks for the bug report. We need an example copybook and a data file in order to check and fix this issue.

**Comment by ss23697** [comment] 2019-11-19 08:55
[0e88fad40214dbe04e42698a5e342a37.zip](https://github.com/AbsaOSS/cobrix/files/3862776/0e88fad40214dbe04e42698a5e342a37.zip)


Hi ,

I have attached sample file and copybook. Its a fixed block file binary file. The last record has incorrect data.

Thanks
Subhankar

**Comment by yruslan** [comment] 2019-11-19 10:02
Cool, will take a look.

**Comment by yruslan** [comment] 2019-11-19 11:18
Can confirm the issue - a very interesting case.

**Comment by yruslan** [comment] 2019-11-19 11:18
Can I add your example to the Cobrix test suite?

**Comment by ss23697** [comment] 2019-11-19 11:24
Hi,

Yes , please. Is there any possible workaround for now to resolve this issue?

Thanks
Subhankar

**Comment by yruslan** [comment] 2019-11-19 11:53
Thanks! No workaround for now. But I hope to fix this quickly.

**Comment by yruslan** [comment] 2019-11-19 13:20
The issue is fixed in `1.1.2-SNAPSHOT`. Please, try and confirm that it is resolved.

**Note**. The snapshot repository is not searched by default, you can enable it temporarily by adding this to your Maven profile:
```
<profiles>
  <profile>
     <id>allow-snapshots</id>
        <activation><activeByDefault>true</activeByDefault></activation>
     <repositories>
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
     </repositories>
   </profile>
</profiles>
```

**Comment by ss23697** [comment] 2019-11-19 14:05
Hi,

We are not using a Maven project. Could you please provide the snapshot jar as we are using the jar in a separate spark script.

Thanks
Subhankar

**Comment by yruslan** [comment] 2019-11-19 14:17
https://drive.google.com/drive/folders/1n3cgUD7Iz57ENukHeO_ML9cQ892bcEJn?usp=sharing

**Comment by ss23697** [comment] 2019-11-20 07:45
Hi,

It is working fine now. Thankyou for the fix.

Thanks
Subhankar

**Comment by yruslan** [comment] 2019-11-20 09:18
👍 Cool, this will be a part of the next release.

**Comment by ss23697** [comment] 2019-11-26 08:22
Hi,

For future release, could you please add data type validation features such as provided by spark.csv . 

We would like to have a way to catch corrupted records during parsing and have a mode like PERMISSIVE where it will put the malformed string into a new field or a mode like DROPMALFORMED where it will drop whole corrupted record or a mode like FAILFAST where it throws exception when it meets corrupted records.

Thanks
Subhankar

**Closed** 2019-11-26 10:46 UTC
Labels: accepted, bug
